package com;

public interface Keys {
	String CURRENT_WORKSPACE = "CURRENT_WORKSPACE";
	String CURRENT_PROJECT = "CURRENT_PROJECT";
	String CURRENT_SOURCE_DIR = "CURRENT_SOURCE_DIR";
	String CURRENT_PACKAGE = "CURRENT_PACKAGE";
	String CURRENT_JAVAFILE = "CURRENT_JAVAFILE";
	String CURRENT_METHOD = "CURRENT_METHOD";
	String CURRENT_FIELD = "CURRENT_FIELD";

}
